FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y libffi-dev
RUN apt-get install -y libstdc++6
RUN apt-get install -y binutils-gold
RUN apt-get install -y gdb


